abstract: Write Python-like generators in Perl
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Compile-Generators
no_index: 
  directory: 
    - inc
    - t
requires: 
  Module::Compile: 0.17
  perl: 5.6.1
version: 0.10
